/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    User: (() => {
      const name = "User";
      return defineComponent(
        world,
        {
          userPosition: RecsType.Number,
          userQuestStatus: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Square: (() => {
      const name = "Square";
      return defineComponent(
        world,
        {
          squareId: RecsType.Number,
          squareCreater: RecsType.String,
          squareDescription: RecsType.String,
          squareImageUrl: RecsType.String,
          squareQuestAddress: RecsType.String,
          squareQuestDescription: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
