/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          playerId: RecsType.String,
          playerBalance: RecsType.Number,
          userPosition: RecsType.Number,
          userQuestStatus: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    
    Square: (() => {
      const name = "Square";
      return defineComponent(
        world,
        {
          gameId: RecsType.Number,
          squareId: RecsType.Number,
          squareCreater: RecsType.String,
          squareDescription: RecsType.String,
          squareImageUrl: RecsType.String,
          squareQuestAddress: RecsType.String,
          squareQuestDescription: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

    Map: (() => {
      const name = "Map";
      return defineComponent(
        world,
        {
          gameId: RecsType.Number,
          mapId: RecsType.Number,
          mapName: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),

  };
}
